version: '3.7'
services:
  node-srv:
    build:
      context: ./docker/
      dockerfile: Dockerfile
    image: node:current-buster
    volumes:
    - ./:/opt/gerqc-bot/
    networks:
      - backend

networks:
  backend:
    driver: bridge